### ISSUE TITLE
Error when tryin Run Custom Tool on VS 2017 prof

### ISSUE THREAD

**Issue by lazycoder-ru** [hybridview/ConfigurationSectionDesigner#2]
And get this error:

An exception occured while running the CsdFileGenerator on this file. See the Error List for details. E=System.InvalidOperationException: Could not find TextTemplate directory. Try reinstalling the Configuration Section Designer.
   at ConfigurationSectionDesigner.CsdFileGenerator.get_TextTemplateFolder()
   at ConfigurationSectionDesigner.CsdFileGenerator.GenerateFromTextTemplate(String fileExtension)
   at ConfigurationSectionDesigner.CsdFileGenerator.GenerateAllContent(String fileExtension)
   at ConfigurationSectionDesigner.CsdFileGenerator.GenerateContent(String element)
   at ConfigurationSectionDesigner.VsMultipleFileGenerator`1.Generate(String wszInputFilePath, String bstrInputFileContents, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, IVsGeneratorProgress pGenerateProgress)

**Comment by hybridview** [comment]
This error is caused when the tool tries to load info from the registry related to the version of this extension is installed, but registry info not found. I saw discrepancies with VSIX version and assembly version, so updated them and released as 2.3.2.1.

**Comment by hybridview** [comment]
User keymarkstuart submitted a pull request that should hopefully prevent this issue from occurring in the future.  I have added a new release with this change.

**Comment by Garwin4j** [comment]
Wonderful, thanks for this.

God Bless!

Yours truly,
Garwin Pryce.

**Comment by hybridview** [comment]
Issue appears to be resolved.
